### ISSUE TITLE
sanity-testing fails: Password prompt

### ISSUE THREAD

**Issue by MarcoFalke** [devrandom/gitian-builder#106]
I just tried to set up fresh target but when running through the sanity test mentioned in [README.md](https://github.com/devrandom/gitian-builder#sanity-testing) I can't get `on-target` working.

It always asks me for a password (I know I can use "ubuntu":"ubuntu" but that's not how gitian should work?)

```
$ on-target -u ubuntu uptime
ubuntu@localhost's password: 
 10:51:41 up 1 min,  0 users,  load average: 0.00, 0.00, 0.00
$ ll var/id_dsa*
-rw-------. 1 marco marco 672 Nov 17 18:24 var/id_dsa
-rw-r--r--. 1 marco marco 635 Nov 17 18:24 var/id_dsa.pub

**Comment by josephbisch** [comment]
I can't reproduce the issue, even with a fresh base. My permissions look the same on my `id_dsa*` files.

What suite are you using? Do any of the log files in var give any more information?

**Comment by MarcoFalke** [comment]
stdout gave me http://pastebin.ubuntu.com/13502921/

The logs in var are empty.

**Comment by josephbisch** [comment]
I think the issue has something to do with the following lines in those stdout logs:

```
2015-11-25 16:04:54,679 INFO    : findfs: unable to resolve 'UUID=82961abe-bdb0-4f0b-8c5b-b337d647e38a'
2015-11-25 16:04:54,680 INFO    : Cannot determine root device.  Assuming /dev/hda1
2015-11-25 16:04:54,680 INFO    : This error is probably caused by an invalid /etc/fstab
```

I just tried recreating my 64-bit Trusty base and I don't get any lines like that. When I do log into the image (using `kvm -m 1024 -smp 1 -drive file=target-trusty-amd64.qcow2` to get a graphical interface to the image), I see GRUB does have `UUID=` lines for me.

What version of vmbuilder are you using?

**Comment by MarcoFalke** [comment]
Great to know the problem probably lies in those three lines.

I am running fedora and as [fedora bug 1074143](https://bugzilla.redhat.com/show_bug.cgi?id=1074143) is not yet resolved I chose to `wget http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz`

So I am running
```
$ vmbuilder --version
2015-11-25 17:28:50,716 INFO    : logging to file: /tmp/tmpl_9NLI
0.12.4
```

`qemu-kvm` gives me:

![screenshot from 2015-11-25 18-05-01](https://cloud.githubusercontent.com/assets/6399679/11403877/7672bb82-939f-11e5-8b2e-77eef7968319.png)
![screenshot from 2015-11-25 18-05-55](https://cloud.githubusercontent.com/assets/6399679/11403866/6c656fd6-939f-11e5-9c27-5a010133646e.png)

**Comment by josephbisch** [comment]
I see you are using a fairly recent vmbuilder bzr revision (494). I think [vmbuilder bzr revision 493](http://bazaar.launchpad.net/~vmbuilder-dev/vmbuilder/0.12/revision/493) might have something to do with the issue. Notice how the fstab template (dapper_fstab.tmpl) was modified to use the UUID instead of `/dev/sda*`. Since I am using an older version of vmbuilder, I have `/dev/sda1` as `/` in my fstab.

If you get past your second screenshot to where you can login, try checking out `/etc/fstab`. See the UUID in there and see if you have it under `/dev/disk/by-uuid/`.

![2015-11-25-121817_1366x768_scrot](https://cloud.githubusercontent.com/assets/665854/11404893/6b24dd5a-9372-11e5-8ec6-1c1e0d46ade5.png)
![2015-11-25-121924_1366x768_scrot](https://cloud.githubusercontent.com/assets/665854/11404892/6b2389e6-9372-11e5-9a07-8b272a8b974b.png)
![2015-11-25-123731_1366x768_scrot](https://cloud.githubusercontent.com/assets/665854/11404894/6b28f44e-9372-11e5-9e75-2d4027e65a15.png)

**Comment by josephbisch** [comment]
Actually, I was wrong. I was able to update vmbuilder, create a new trusty image, and still not have any issue sshing to that image.

So it seems to have nothing to do with that vmbuilder revision that I thought it might have something to do with.

**Comment by MarcoFalke** [comment]
Screens look just fine:

![screenshot from 2015-11-30 18-56-34](https://cloud.githubusercontent.com/assets/6399679/11479841/580cd49a-9794-11e5-83f3-dcd808fb7ca9.png)
![screenshot from 2015-11-30 18-56-16](https://cloud.githubusercontent.com/assets/6399679/11479843/594ca088-9794-11e5-9c80-991300cd6249.png)

**Comment by josephbisch** [comment]
Maybe try adding `-vvv` to the ssh command in libexec/on-target and see if that outputs any useful messages?
