### ISSUE TITLE
Issue with Debian 9 - stretch

### ISSUE THREAD

**Issue by jonasschnelli** [devrandom/gitian-builder#147]
I just upgraded from Debian 8 to Debian 9 and ran into the following issue while gbuild.
make-base-vm works fine.
I can also execute `on-target` commands or run the on-target shell (`sudo lxc-execute -n gitian -f var/lxc.config -- sudo -u root  -I -- bash`)

```
init.lxc: failed to mount /dev/shm : No such file or directory
sudo: unknown user: ubuntu
sudo: unable to initialize policy plugin
```

**Comment by jonasschnelli** [comment]
Could solve the issue by...

... adding a mount point to `etc/lxc.config.in`:
`lxc.mount.entry=shm dev/shm tmpfs rw,nodev,noexec,nosuid,relatime,mode=1777,create=dir 0 0`

... adding fixes to bootstrap-fixups.in
```diff
diff --git a/target-bin/bootstrap-fixup.in b/target-bin/bootstrap-fixup.in
index 222b368..da594ae 100755
--- a/target-bin/bootstrap-fixup.in
+++ b/target-bin/bootstrap-fixup.in
@@ -22,6 +22,9 @@ fi
 echo '127.0.1.1 gitian' >> /etc/hosts
 
 # If LXC
+mkdir /home/ubuntu
+useradd ubuntu -d /home/ubuntu
+chown ubuntu.ubuntu /home/ubuntu
 if grep /lxc/gitian /proc/1/cgroup > /dev/null; then
   adduser --disabled-password --gecos ${DISTRIB_NAME,,} --quiet ${DISTRIB_NAME,,} || true
   apt-get remove -y rsyslog || true
```

**Comment by josephbisch** [comment]
Thanks.

This only affects LXC, right? Then I would put the `bootstrap-fixups.in` changes within the if statement (it looks like that is what you were trying to do, since you put the changes below the LXC comment, but you put the changes too high to actually only affect LXC).

I would also replace the use of `ubuntu` with `${DISTRIB_NAME,,}` so that the changes don't break Debian guests. I.e., we are replacing the variable with `debian` if a Debian guest is being used or `ubuntu` if an Ubuntu guest is being used to reflect the default user account for each distro.

**Comment by jonasschnelli** [comment]
@josephbisch: I'm not very familiar with Gitian. Would be great if you could do a PR...

**Comment by josephbisch** [comment]
@jonasschnelli Okay, I'll do that.
