### ISSUE TITLE
PR#150 gives errors for mounting shm

### ISSUE THREAD

**Issue by Earlz** [devrandom/gitian-builder#151]
I'm following the Bitcoin walkthrough for doing Gitian builds using Debian 8.5 packages etc. I did this setup last week and I had to chase down a few problems, but overall it worked pretty well. Today when I tried to set it up again I got this error:
```
lxc-execute: Mount onto /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/shm resulted in /dev/shm, does not match root /usr/lib/x86_64-linux-gnu/lxc/rootfs

lxc-execute: Mount of 'shm' onto '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/shm' was onto a symlink!
lxc-execute: File exists - failed to mount 'shm' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/shm'
lxc-execute: failed to setup the mount entries for 'gitian'
lxc-execute: failed to setup the container
lxc-execute: invalid sequence number 1. expected 2
lxc-execute: failed to spawn 'gitian'
```

I rolled back commit c2ff3f9025ab6d5c7bc8bbfbd72f79d40e119401 from #150 and the error went away and everything seems to function as normal

**Comment by josephbisch** [comment]
AFAIK, the messages that went away after adding the mount in c2ff3f9025ab6d5c7bc8bbfbd72f79d40e119401 were just warnings and not actually preventing Gitian from working. So we should be able to revert that commit.

I'm not sure if this is an LXC issue or a debootstrap issue. Jessie itself has LXC 1.0, whereas jessie-backports and stretch have LXC 2.0. But there are also differences between debootstrap in jessie and the one in jessie-backports/stretch.

Here is the deboostrap in jessie that doesn't create a /dev/shm:
http://sources.debian.net/src/debootstrap/1.0.67%2Bdeb8u1/Makefile/#L38

Here is the debootstrap in jessie-backports/stretch that does create a /dev/shm:
http://sources.debian.net/src/debootstrap/1.0.89/functions/#L1173

So, based on the error messages you pasted, on jessie, the container ends up with a symlink for /dev/shm and the mount fails. Removing the symlink should help, but you've already found that rolling back the commit fixes this.

Until we have more insight into what is causing the differences between jessie and stretch that result in this issue and are therefore able to implement a fix that works for both jessie and stretch, we should take some action to not leave gitian-builder broken on a release of a major OS.

Since the Bitcoin documentation recommends using jessie for gitian builds, dropping support for jessie is not a viable option.

It seems that the Bitcoin documentation isn't using backports. Since key packages such as lxc and debootstrap would then be the same version as in stretch, this problem should go away if we recommend the use of jessie-backports if you are using jessie. However, I am not sure how that change would affect Bitcoin, since it is possible comparing builds from before the change to after the change might no longer be reproducible as a result of the different package versions.

Probably the best course of action is to revert the commit for now. AFAIK, no software uses gitian with stretch. It's particularly unlikely, since there has been such a small window of time since that commit.
