### ISSUE TITLE
How to compile based on local directory?

### ISSUE THREAD

**Issue by lucaszanella** [devrandom/gitian-builder#169]
I cannot find easily a documentation about yml files. For example, I tried for the linux kernel:

```
---
name: "kernel-linux-"
enable_cache: true
suites:
- "trusty"
architectures:
- "amd64"
packages:
- "fakeroot"
- "build-essential"
- "ncurses-dev"
- "xz-utils"
- "libssl-dev"
- "bc"
files: ["/home/lz/Downloads/linux-4.16-rc1/linux-4.16-rc1"]
script: |
  sudo make -j 4 && sudo make modules_install -j 4
```

But this produces: 

```
lz@air:~/gitian-builder$ bin/gbuild /home/lz/Desktop/linux.yml
bin/gbuild:239:in `<main>': undefined method `size' for nil:NilClass (NoMethodError)

```

so what are the files for? Would be glad to have a little help with this. Would be nice to have some yml classical examples like the linux kernel. I could add them later in a folder, I'm really into this project, I'm gonna include files for each of my projects now

**Comment by josephbisch** [comment]
Looking at that line of gbuild, it appears to be because of there being no remotes in that descriptor. Looking at [one of the Bitcoin Core descriptors](https://github.com/bitcoin/bitcoin/blob/d7f438a026cb67f2aa8d12d94def9c6be2d9aa97/contrib/gitian-descriptors/gitian-linux.yml#L30-L32), you can see an example of the syntax. It specifies the git repo that should be cloned. It is whatever software you are trying to build (like the Linux kernel).

If you are trying to build software that is local (that is what you appear to be doing) instead of cloning software from a git repo, you can take a look at [this descriptor](https://github.com/JeremyRand/sqlite-gitian/blob/master/gitian-descriptors/sqlite-linux.yml) as an example of how to do a build without any repo.

The descriptors (the yaml files) are to define metadata about the build and how to do the build. Gitian itself doesn't know how to build software unless you write a descriptor telling it how to do the build.

**Comment by lucaszanella** [comment]
Thank you so much. I don't wanna be irritating, but why I cannot put total paths in files? 
```

files:
- "/home/lz/Downloads/linux-4.16-rc1.tar.gz"
```

gives me 

```
bin/gbuild:25:in `sanitize': unsanitary string in files section (RuntimeError)
	from bin/gbuild:248:in `block in <main>'
	from bin/gbuild:247:in `each'
	from bin/gbuild:247:in `<main>'
```

**Comment by josephbisch** [comment]
If I remember correctly, I believe the files go in a directory named `inputs` within the gitian-builder repo. So the file paths are supposed to be relative to that `inputs` directory. So I would just put the `linux-4.16-rc1.tar.gz` file in the `inputs` directory and then change that to

```
file:
- "linux-4.16-rc1.tar.gz"
```

**Comment by jonathancross** [comment]
@lucaszanella Can this be closed?

**Comment by devrandom** [comment]
stale
