### ISSUE TITLE
doesn't seems to work on debian host

### ISSUE THREAD

**Issue by jonasschnelli** [devrandom/gitian-builder#76]
On debian i got errors complaining a missing ubuntu keyring.
Looking at https://github.com/devrandom/gitian-builder/blob/master/bin/make-base-vm makes me feel that gitian requires ubuntu.

**Comment by josephbisch** [comment]
You have probably moved on or figured this out since you opened this issue, but I use Debian as the host for Gitian fine. You just have to run the following on Debian Jessie or newer:

```
sudo apt-get install ubuntu-archive-keyring
```

On Debian Wheezy you run the same command, but you must first add backports to your system, because the package is only available in wheezy-backports.

**Comment by devrandom** [comment]
@josephbisch thank you!  Added this text in https://github.com/devrandom/gitian-builder/commit/f8a3307bc866019ef702597e7e800b39252ff560 .
